---
layout: cv
title: Raydon Diab's CV
---
# Raydon Diab
Data Scientist, Mathematician, Judoka.

<div id="webaddress">
<a href="dia24027@byui.edu">dia24027@byui.edu</a>
| <a href="https://www.youtube.com/watch?v=xvFZjo5PgG0&list=RDxvFZjo5PgG0&start_radio=1">My wikipedia page</a>
</div>


## Currently

Living my best life at Brigham Young University - Idaho.

### Specialized in

Reading and presenting data analysis, learning new skills.


### Research interests

Sports betting, finance.


## Education

`2006-2013`
__Ridgevale Primary School__

`2014-2018`
__St. Ursula's High School__

- Marticulant

`2018-2019`
__International Judo Federation Academy in Association with the University of Hungary__

- Certification in Sports Instruction

`2024-now`
__Brigham Young University-Idaho__

- Currently studying Data science with a minor in AI engineering



## Awards

`2010-2018`
10x South African National Champion in Judo



## Publications

Sadly, none yet.


### Patents



## Occupation

`2012-2022`
__Kuzushi Judo Club__, Johannesburg

- Taught judo classes
- Led athletes to national tournaments

`2024-2024`
__Clearwater Services__, Johannesburg

- Created marketing advertisements
- Led weekly meetings to discuss advertising outreach efforts.



<!-- ### Footer

Last updated: May 2013 -->